CREATE DATABASE cinema;
USE cinema;
CREATE TABLE movies (id INT PRIMARY KEY, title VARCHAR(255), description VARCHAR(255), rating FLOAT, image VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP);